[package]
name = "arduino_probe"
version = "0.1.0"
authors = ["Marek Černoch <marek.cernoch@email.cz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serial-core = "0.4"
serial = "0.4"